=== struqt/invar/res/example/data/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:tns="invar.data" targetNamespace="invar.data">

<xs:element name="root" type="tns:test.xyz.ConfigRoot" />

<xs:complexType name="int8"><xs:attribute type="xs:byte" name="value" use="required"/></xs:complexType>
<xs:complexType name="int16"><xs:attribute type="xs:short" name="value" use="required"/></xs:complexType>
<xs:complexType name="int32"><xs:attribute type="xs:int" name="value" use="required"/></xs:complexType>
<xs:complexType name="int64"><xs:attribute type="xs:long" name="value" use="required"/></xs:complexType>
<xs:complexType name="uint8"><xs:attribute type="xs:unsignedByte" name="value" use="required"/></xs:complexType>
<xs:complexType name="uint16"><xs:attribute type="xs:unsignedShort" name="value" use="required"/></xs:complexType>
<xs:complexType name="uint32"><xs:attribute type="xs:unsignedInt" name="value" use="required"/></xs:complexType>
<xs:complexType name="uint64"><xs:attribute type="xs:unsignedLong" name="value" use="required"/></xs:complexType>
<xs:complexType name="float"><xs:attribute type="xs:float" name="value" use="required"/></xs:complexType>
<xs:complexType name="double"><xs:attribute type="xs:double" name="value" use="required"/></xs:complexType>
<xs:complexType name="bool"><xs:attribute type="xs:boolean" name="value" use="required"/></xs:complexType>
<xs:complexType name="string"><xs:attribute type="xs:string" name="value" use="required"/></xs:complexType>

<xs:complexType name="test.xyz.InfoX">
  <xs:sequence>
    <xs:element name="conflict_x" minOccurs="0" maxOccurs="2048" type="tns:test.xyz.Conflict" />
    <xs:element name="conflict_a" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Conflict" />
    <xs:element name="mConflict" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="Conflict" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Conflict" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="info2d" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="vec" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="info3d" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="vec" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="vec" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="infovm" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="map" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mvei" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="2048">
      <xs:element name="k-vec" minOccurs="1" maxOccurs="1" >
      <xs:complexType><xs:sequence>
      <xs:element name="Gender" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Gender" />
      </xs:sequence></xs:complexType>
      </xs:element>
      <xs:element name="v-Info" minOccurs="1" maxOccurs="1" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mive" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="2048">
      <xs:element name="k-Info" minOccurs="1" maxOccurs="1" type="tns:test.abc.Info" />
      <xs:element name="v-vec" minOccurs="1" maxOccurs="1" >
      <xs:complexType><xs:sequence>
      <xs:element name="Gender" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Gender" />
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mvive" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="2048">
      <xs:element name="k-vec" minOccurs="1" maxOccurs="1" >
      <xs:complexType><xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
      </xs:element>
      <xs:element name="v-vec" minOccurs="1" maxOccurs="1" >
      <xs:complexType><xs:sequence>
      <xs:element name="Gender" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Gender" />
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="vmvive" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="map" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="2048">
      <xs:element name="k-vec" minOccurs="1" maxOccurs="1" >
      <xs:complexType><xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
      </xs:element>
      <xs:element name="v-vec" minOccurs="1" maxOccurs="1" >
      <xs:complexType><xs:sequence>
      <xs:element name="Gender" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Gender" />
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="test.xyz.Conflict">
  <xs:sequence>
    <xs:element name="pi" minOccurs="0" maxOccurs="2048" type="tns:double" />
  </xs:sequence>
  <xs:attribute name="pi" type="xs:double" />
</xs:complexType>
<xs:complexType name="test.xyz.ConfigRoot">
  <xs:sequence>
    <xs:element name="revision" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
    <xs:element name="infox" minOccurs="0" maxOccurs="2048" type="tns:test.xyz.InfoX" />
  </xs:sequence>
  <xs:attribute name="revision" type="xs:string" />
</xs:complexType>
<xs:complexType name="test.abc.Gender"><xs:attribute type="tns:test.abc.GenderAttr" name="value" use="required" /></xs:complexType>
<xs:simpleType name="test.abc.GenderAttr">
  <xs:restriction base="int">
    <!-- MALE --><xs:enumeration value="1" />
    <!-- FEMALE --><xs:enumeration value="2" />
    <!-- NONE --><xs:enumeration value="10" />
  </xs:restriction></xs:simpleType>
<xs:complexType name="test.abc.Info">
  <xs:sequence>
    <xs:element name="key" minOccurs="0" maxOccurs="2048" type="tns:int32" />
    <xs:element name="number01" minOccurs="0" maxOccurs="2048" type="tns:int8" />
    <xs:element name="number02" minOccurs="0" maxOccurs="2048" type="tns:int16" />
    <xs:element name="number03" minOccurs="0" maxOccurs="2048" type="tns:int32" />
    <xs:element name="number04" minOccurs="0" maxOccurs="2048" type="tns:int64" />
    <xs:element name="number05" minOccurs="0" maxOccurs="2048" type="tns:uint8" />
    <xs:element name="number06" minOccurs="0" maxOccurs="2048" type="tns:uint16" />
    <xs:element name="number07" minOccurs="0" maxOccurs="2048" type="tns:uint32" />
    <xs:element name="number08" minOccurs="0" maxOccurs="2048" type="tns:uint64" />
    <xs:element name="number09" minOccurs="0" maxOccurs="2048" type="tns:float" />
    <xs:element name="number10" minOccurs="0" maxOccurs="2048" type="tns:double" />
    <xs:element name="isReal" minOccurs="0" maxOccurs="2048" type="tns:bool" />
    <xs:element name="s" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="gender" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Gender" />
    <xs:element name="next" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
    <xs:element name="conflict" minOccurs="0" maxOccurs="2048" type="tns:test.xyz.Conflict" />
    <xs:element name="infos" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mapInfoG" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="2048">
      <xs:element name="k-Info" minOccurs="1" maxOccurs="1" type="tns:test.abc.Info" />
      <xs:element name="v-Gender" minOccurs="1" maxOccurs="1" type="tns:test.abc.Gender" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mapGenderInfo" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="Info" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Info" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="mapDouble" minOccurs="0" maxOccurs="2048" >
      <xs:complexType>
      <xs:sequence>
      <xs:element name="double" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:complexContent>
      <xs:extension base="tns:double">
      <xs:attribute name="key" type="xs:string" use="required" />
      </xs:extension></xs:complexContent></xs:complexType>
      </xs:element>
      </xs:sequence></xs:complexType>
    </xs:element>
  </xs:sequence>
  <xs:attribute name="key" type="xs:int" />
  <xs:attribute name="number01" type="xs:byte" />
  <xs:attribute name="number02" type="xs:short" />
  <xs:attribute name="number03" type="xs:int" />
  <xs:attribute name="number04" type="xs:long" />
  <xs:attribute name="number05" type="xs:unsignedByte" />
  <xs:attribute name="number06" type="xs:unsignedShort" />
  <xs:attribute name="number07" type="xs:unsignedInt" />
  <xs:attribute name="number08" type="xs:unsignedLong" />
  <xs:attribute name="number09" type="xs:float" />
  <xs:attribute name="number10" type="xs:double" />
  <xs:attribute name="isReal" type="xs:boolean" />
  <xs:attribute name="s" type="xs:string" />
  <xs:attribute name="gender" type="tns:test.abc.GenderAttr" />
</xs:complexType>
<xs:complexType name="test.abc.Conflict">
  <xs:sequence>
    <xs:element name="text" minOccurs="0" maxOccurs="2048" type="tns:string" />
    <xs:element name="bytes" minOccurs="0" maxOccurs="2048" >
      <xs:complexType><xs:sequence>
      <xs:element name="int8" minOccurs="0" maxOccurs="2048" type="tns:int8" />
      </xs:sequence></xs:complexType>
    </xs:element>
    <xs:element name="key" minOccurs="0" maxOccurs="2048" type="tns:test.abc.Gender" />
  </xs:sequence>
  <xs:attribute name="text" type="xs:string" />
  <xs:attribute name="key" type="tns:test.abc.GenderAttr" />
</xs:complexType>
</schema>

=== struqt/invar/invar-example/example/data/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- abc -->
<tns:root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invar.data data.xsd"
	xmlns:tns="invar.data">

	<revision value="1.0.2" />
	<revision value="1.0.3" />
	<revision value="1.0.4" />
	


<!-- 
Info info = new Info();
info.getMapDouble().put("a", 1.0);
info.getMapDouble().put("b", 2.0);
System.out.println(info.toXmlString("ss"));
-->
<!--
<f1 f0="88" f1="-1" f2="-1" f3="-1" f4="0" f5="0" f6="0" f7="0" f8="0.0" f9="0.0" f10="false" f11="" f12="-1" f13="1">
<f18>
	<x key="0" value="0" />
	<x key="0" value="0" />
</f18>
</f1>
-->
	<info gender="2" isReal="true">
		<number02 value="2" />
		<next number01="-128" number02="-32768">
			<number01 value="127" />
			<number02 value="32767" />
			<number03 value="2147483647" />
			<number04 value="-9223372036854775808" />
			<number04 value="9223372036854775807" />
			<number05 value="255" />
			<number06 value="65535" />
			<number07 value="4294967295" />
			<number08 value="18223372036854775807" />
			<number09 value="98.7654321" />
			<number10 value="987654321.123456789" />
			<isReal value="true" />
			<s value="China" />
			<gender value="10" />
			<infos>
				<Info s="A" number02="32767" />
				<Info s="B" number08="28" />
				<Info s="C" number08="38" />
			</infos>
			<mapInfoG>
				<k-Info s="one" />
				<v-Gender value="1" />
				<k-Info s="two" />
				<v-Gender value="2" />
				<k-Info s="ten" />
				<v-Gender value="10" />
			</mapInfoG>
			<mapInfoG>
				<k-Info s="#one" />
				<v-Gender value="1" />
				<k-Info s="#two" />
				<v-Gender value="2" />
				<k-Info s="#ten" />
				<v-Gender value="10" />
			</mapInfoG>
			<mapGenderInfo>
				<Info key="1" />
				<Info key="2" />
			</mapGenderInfo>
		</next>
	</info>

	<!-- complex data -->
	<infox>
		<conflict_x pi="3.1416" />
		<conflict_a>
			<bytes>
				<int8 value="-128" />
				<int8 value="127" />
				<int8 value="100" />
				<int8 value="101" />
				<int8 value="108" />
				<int8 value="120" />
			</bytes>
		</conflict_a>
		<mConflict>
			<Conflict key="1">
				<bytes>
					<int8 value="-128" />
					<int8 value="127" />
				</bytes>
			</Conflict>
			<Conflict key="2"></Conflict>
		</mConflict>
		<info2d>
			<vec>
				<Info isReal="true" number07="4294967295" />
				<Info isReal="false" number07="02" />
			</vec>
			<vec>
				<Info s="AAAAA" />
				<Info s="BBBBB" />
			</vec>
		</info2d>
		<info3d>
			<vec>
				<vec>
					<Info s="000" />
					<Info s="001" />
					<Info s="002" />
				</vec>
				<vec>
					<Info s="010" />
					<Info s="011" />
					<Info s="012" />
				</vec>
				<vec>
					<Info s="020" />
					<Info s="021" />
					<Info s="022" />
				</vec>
			</vec>
			<vec>
				<vec>
					<Info s="100" />
					<Info s="101" />
					<Info s="102" />
				</vec>
				<vec>
					<Info s="110" />
					<Info s="111" />
					<Info s="112" />
				</vec>
			</vec>
		</info3d>
		<infovm>
			<map>
				<Info key="666" isReal="true" />
				<Info key="888" isReal="true" />
			</map>
			<map>
				<Info key="777" isReal="true" />
				<Info key="999" isReal="true" />
			</map>
		</infovm>
		<mvei>
			<k-vec>
				<Gender value="1" />
				<Gender value="10" />
			</k-vec>
			<v-Info s="mvei001" number09=".64" />
			<k-vec>
				<Gender value="10" />
				<Gender value="2" />
			</k-vec>
			<v-Info s="mvei002">
				<number10 value=".2" />
			</v-Info>
		</mvei>

		<mive>
			<k-Info s="mive.0" />
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
			<k-Info s="mive.1" />
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
			<k-Info s="mive.2" />
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
		</mive>
		<mive>
			<k-Info s="mive.100" />
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
			<k-Info s="mive.101" />
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
			<k-Info s="mive.102" />
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
		</mive>

		<mvive>
			<k-vec>
				<Info s="mvive" />
				<Info s="mvive" />
				<Info s="mvive" />
			</k-vec>
			<v-vec>
				<Gender value="1" />
				<Gender value="2" />
			</v-vec>
		</mvive>

		<vmvive>
			<map>
				<k-vec>
					<Info s="vmvive.a" />
					<Info s="vmvive.a" />
					<Info s="vmvive.a" />
				</k-vec>
				<v-vec>
					<Gender value="1" />
				</v-vec>
				<k-vec>
					<Info s="vmvive.a" />
					<Info s="vmvive.a" />
					<Info s="vmvive.a" />
				</k-vec>
				<v-vec>
					<Gender value="1" />
				</v-vec>
			</map>
			<map>
				<k-vec>
					<Info s="vmvive.b" />
					<Info s="vmvive.b" />
				</k-vec>
				<v-vec>
					<Gender value="2" />
					<Gender value="10" />
				</v-vec>
				<k-vec>
					<Info s="vmvive.b" />
					<Info s="vmvive.b" />
				</k-vec>
				<v-vec>
					<Gender value="2" />
					<Gender value="10" />
				</v-vec>
			</map>
		</vmvive>
	</infox>

</tns:root>
