=== struqt/invar/res/example/rule/rule.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="invar.rule"
  targetNamespace="invar.rule">
  <xs:element name="package" type="tns:rule.package">
    <xs:annotation>
      <xs:documentation>Define a package</xs:documentation>
      <xs:appinfo>Application Information</xs:appinfo>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="rule.package">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="enum" type="tns:rule.enum" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="struct" type="tns:rule.struct" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="protoc" type="tns:rule.protoc" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="alias" type="xs:string" use="optional"/>
    <xs:attribute name="doc" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="rule.protoc">
    <xs:all>
      <xs:element name="client" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" type="tns:rule.struct.field" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="server" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" type="tns:rule.struct.field" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="doc" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="rule.struct.field">
    <xs:attribute name="type" type="tns:rule.type" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="doc" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
    <xs:attribute name="deprecated" type="xs:boolean" use="optional"/>
    <xs:attribute name="nosetter" type="xs:boolean" use="optional"/>
    <xs:attribute name="useref" type="xs:boolean" use="optional"/>
    <xs:attribute name="useptr" type="xs:boolean" use="optional"/>
    <xs:attribute name="scope" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="public"/>
          <xs:enumeration value="protected"/>
          <xs:enumeration value="private"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="rule.struct">
    <xs:sequence>
      <xs:element name="field" type="tns:rule.struct.field" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="doc" type="xs:string" use="required"/>
    <xs:attribute name="super" type="xs:string" use="optional"/>
    <xs:attribute name="short" type="xs:string" use="optional"/>
    <xs:attribute name="alias" type="xs:string" use="optional"/>
    <xs:attribute name="nohotfix" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="rule.enum">
    <xs:sequence>
      <xs:element name="option" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="name" type="xs:string" use="required"/>
          <xs:attribute name="value" type="xs:int" use="required"/>
          <xs:attribute name="doc" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="doc" type="xs:string" use="required"/>
    <xs:attribute name="alias" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:simpleType name="rule.type">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Int8"/>
          <xs:enumeration value="Int16"/>
          <xs:enumeration value="Int32"/>
          <xs:enumeration value="Int64"/>
          <xs:enumeration value="Uint8"/>
          <xs:enumeration value="Uint16"/>
          <xs:enumeration value="Uint32"/>
          <xs:enumeration value="Uint64"/>
          <xs:enumeration value="Float"/>
          <xs:enumeration value="Double"/>
          <xs:enumeration value="Bool"/>
          <xs:enumeration value="String"/>
          <xs:enumeration value="Vec-Int8"/>
          <xs:enumeration value="Vec-Int16"/>
          <xs:enumeration value="Vec-Int32"/>
          <xs:enumeration value="Vec-Int64"/>
          <xs:enumeration value="Vec-Uint8"/>
          <xs:enumeration value="Vec-Uint16"/>
          <xs:enumeration value="Vec-Uint32"/>
          <xs:enumeration value="Vec-Uint64"/>
          <xs:enumeration value="Vec-Float"/>
          <xs:enumeration value="Vec-Double"/>
          <xs:enumeration value="Vec-Bool"/>
          <xs:enumeration value="Vec-String"/>
          <xs:enumeration value="Map-Int8"/>
          <xs:enumeration value="Map-Int16"/>
          <xs:enumeration value="Map-Int32"/>
          <xs:enumeration value="Map-Int64"/>
          <xs:enumeration value="Map-Uint8"/>
          <xs:enumeration value="Map-Uint16"/>
          <xs:enumeration value="Map-Uint32"/>
          <xs:enumeration value="Map-Uint64"/>
          <xs:enumeration value="Map-Float"/>
          <xs:enumeration value="Map-Double"/>
          <xs:enumeration value="Map-Bool"/>
          <xs:enumeration value="Map-String"/>
          <xs:enumeration value="Map-Int32-String"/>
          <xs:enumeration value="Map-Int32-Bool"/>
          <xs:enumeration value="Map-Int32-Vec-String"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="[A-Za-z]+[A-Za-z0-9_.:]*"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="(Vec\-)+[A-Za-z]+[A-Za-z0-9_.:]*"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="(Map)+(\()[A-Za-z]+[A-Za-z0-9_.:,\(\)]*\)"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="(Map\-)+[A-Za-z]+[A-Za-z0-9_.:\(\)]*"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="(Vec\-)+(Map)+((\-[A-Za-z]+[A-Za-z0-9_.:]*)|(\-(Vec\-)+[A-Za-z_]+[A-Za-z0-9_.:]*)){1,2}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="(Map)+((\-[A-Za-z_]+[A-Za-z0-9_.:]*)|(\-(Vec\-)+[A-Za-z_]+[A-Za-z0-9_.:]*)){1,2}"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
</schema>

=== struqt/invar/res/example/rule/abc.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:package name="test.abc"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="invar.rule rule.xsd"
xmlns:tns="invar.rule">

  <struct name="Conflict" doc="名字冲突的类型">
    <field name="key" type="Gender" doc=""/>
    <field name="text" type="String" doc=""/>
    <field name="bytes" type="Vec-Int8" doc=""/>
  </struct>
  
  <enum name="Gender" doc="性别的枚举类型">
    <option name="NONE" value="-1" doc=""/>
    <option name="MALE" value="10" doc="Enum male"/>
    <option name="FEMALE" value="20" doc="Enum female"/>
  </enum>
  
  <struct name="Custom" doc="自定义类型">
  	<field name="x" type="Gender" doc="枚举值"/>
    <field name="test" type="TestBasic" doc="其他类型"/>
  	<field name="xyz" type="test.xyz::Conflict" doc="同名的类型"/>
  	<field name="abc" type="test.abc::Conflict" doc="同名的类型"/>
    <field name="children" type="Vec-Custom" doc="自身类型容器"/>
    <field name="noSetter" type="Int32" doc="屏蔽Setter" nosetter="true" deprecated="true"/>
    <field name="useRef" type="Int32" doc="使用引用" useref="true"/>
    <field name="usePtr" type="Int32" doc="使用指针" useptr="true"/>
    <field name="prev" type="Custom" doc="自身类型"/>
    <field name="next" type="Custom" doc="自身类型"/>
  </struct>
  
  <struct name="TestBasic" doc="基础类型">
  	<field name="numberi08" type="Int8" doc="有符号的8位整数"/>
    <field name="numberi16" type="Int16" doc="有符号的16位整数"/>
    <field name="numberi32" type="Int32" value="123" doc="有符号的32位整数"/>
    <field name="numberi64" type="Int64" doc="有符号的64位整数"/>
    <field name="numberu08" type="Uint8" doc="无符号的8位整数"/>
    <field name="numberu16" type="Uint16" doc="无符号的16位整数"/>
    <field name="numberu32" type="Uint32" doc="无符号的32位整数"/>
    <field name="numberu64" type="Uint64" doc="无符号的64位整数"/>
    <field name="numberSingle" type="Float" value="3.14" doc="单精度浮点小数"/>
    <field name="numberDouble" type="Double" doc="双精度浮点小数"/>
    <field name="boolValue" type="Bool" doc="布尔值"/>
    <field name="stringValue" type="String" value="hello" doc="字符串"/>
    <field name="enumValue" type="Gender" doc="枚举值"/>
    <field name="enumDeft" type="Gender" doc="枚举值制定默认值" value="Gender.MALE"/>
  </struct>
  
  <protoc name="TestProtoc" doc="">
    <server>
      <field name="info" type="Info" doc=""/>
    </server>
    <client>
      <field name="gender" type="Gender" doc=""/>
      <field name="info" type="Info" doc=""/>
      <field name="message" type="String" doc=""/>
    </client>
  </protoc>

  <struct name="Info" short="f" doc="Test comments">
    <field name="key" value="123" type="Int32" doc=""/>
    <field name="number01" type="Int8" doc=""/>
    <field name="number02" type="Int16" doc=""/>
    <field name="number03" type="Int32" doc=""/>
    <field name="number04" type="Int64" doc="Test field comments"/>
    <field name="number05" type="Uint8" doc=""/>
    <field name="number06" type="Uint16" doc=""/>
    <field name="number07" type="Uint32" doc=""/>
    <field name="number08" type="Uint64" doc=""/>
    <field name="number09" type="Float" doc=""/>
    <field name="number10" type="Double" doc=""/>
    <field name="isReal" type="Bool" doc=""/>
    <field name="s" type="String" value="hello" scope="public" doc="a string"/>
    <field name="world" type="Vec-String" doc=""/>
    <field name="gender" type="Gender" doc=""/>
    <field name="next" type="Info" doc=""/>
    <field name="conflict" type="test.abc::Conflict" doc=""/>
    <field name="conflicts" type="Vec-test.xyz::Conflict" doc=""/>
    <field name="numbers" type="Vec-Double" doc=""/>    
    <field name="mapInfoG" type="Map-Info-Gender" doc=""/>
    <field name="mapGenderInfo" type="Map-Gender-Info" doc=""/>
    <field name="mapDouble" type="Map-Double" doc=""/>
    <!-- 
    <field name="mapDouble2" type="Map(Int32,Vec(Info))" doc=""/>
    -->
  </struct>
</tns:package>

=== struqt/invar/example/rule/zyz.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:package name="test.xyz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invar.rule rule.xsd"
  xmlns:tns="invar.rule">
  <struct name="TestList" doc="测试基本的列表类型">
    <field name="listI08" type="Vec-Int8" doc="有符号的8位整数"/>
    <field name="listI16" type="Vec-Int16" doc="有符号的16位整数"/>
    <field name="listI32" type="Vec-Int32" doc="有符号的32位整数"/>
    <field name="listI64" type="Vec-Int64" doc="有符号的64位整数"/>
    <field name="listU08" type="Vec-Uint8" doc="无符号的8位整数"/>
    <field name="listU16" type="Vec-Uint16" doc="无符号的16位整数"/>
    <field name="listU32" type="Vec-Uint32" doc="无符号的32位整数"/>
    <field name="listU64" type="Vec-Uint64" doc="无符号的64位整数"/>
    <field name="listSingle" type="Vec-Float" doc="单精度浮点小数"/>
    <field name="listDouble" type="Vec-Double" doc="双精度浮点小数"/>
    <field name="listBoolean" type="Vec-Bool" doc="布尔值"/>
    <field name="listString" type="Vec-String" doc="字符串"/>
    <field name="listEnum" type="Vec-Gender" doc="枚举值" nosetter="false"/>
    <field name="listStruct" type="Vec-Custom" doc="自定义结构"/>
  </struct>
  <struct name="TestDict" doc="测试基本的映射类型">
    <field name="dictI08" type="Map-Int8-Int8" doc="有符号的8位整数"/>
    <field name="dictI16" type="Map-Int16-Int16" doc="有符号的16位整数"/>
    <field name="dictI32" type="Map-Int32-Int32" doc="有符号的32位整数"/>
    <field name="dictI64" type="Map-Int64-Int64" doc="有符号的64位整数"/>
    <field name="dictU08" type="Map-Uint8-Uint8" doc="无符号的8位整数"/>
    <field name="dictU16" type="Map-Uint16-Uint16" doc="无符号的16位整数"/>
    <field name="dictU32" type="Map-Uint32-Uint32" doc="无符号的32位整数"/>
    <field name="dictU64" type="Map-Uint64-Uint64" doc="无符号的64位整数"/>
    <field name="dictSingle" type="Map-Float-Float" doc="单精度浮点小数"/>
    <field name="dictDouble" type="Map-Double-Double" doc="双精度浮点小数"/>
    <field name="dictBoolean" type="Map-Bool-Bool" doc="布尔值"/>
    <field name="dictString" type="Map-String-String" doc="字符串"/>
    <field name="dictEnum" type="Map-Gender-Gender" doc="枚举值"/>
    <field name="dictStruct" type="Map-Custom-Custom" doc="自定义结构"/>
  </struct>
  <struct name="TestNest" doc="测试泛型相互嵌套">
    <field name="listDict" type="Vec-Map-String-Custom" doc=""/>
    <field name="dictList" type="Map-Vec-String-Vec-Custom" doc=""/>
    <field name="list5d" type="Vec-Vec-Vec-Vec-Vec-Custom" doc="五维列表"/>
  </struct>
  <struct name="TestRefer" doc="引用类型测试">
    <field name="numberi08" type="Int8" useref="true" doc=""/>
    <field name="numberi16" type="Int16" useref="true" doc=""/>
    <field name="numberi32" type="Int32" useref="true" doc=""/>
    <field name="numberi64" type="Int64" useref="true" doc=""/>
    <field name="numberu08" type="Uint8" useref="true" doc=""/>
    <field name="numberu16" type="Uint16" useref="true" doc=""/>
    <field name="numberu32" type="Uint32" useref="true" doc=""/>
    <field name="numberu64" type="Uint64" useref="true" doc=""/>
    <field name="numberSingle" type="Float" useref="true" doc=""/>
    <field name="numberDouble" type="Double" useref="true" doc=""/>
    <field name="boolValue" type="Bool" useref="true" doc=""/>
    <field name="stringValue" type="String" useref="false" doc=""/>
    <field name="enumValue" type="Gender" useref="true" doc=""/>
    <field name="other" type="Custom" useref="false" doc=""/>
    <field name="self" type="TestRefer" useref="true" doc=""/>
    <field name="listI08" type="Vec-Int8" useref="false" doc=""/>
    <field name="dictI08" type="Map-Int8-Int8" useref="false" doc=""/>
  </struct>
  <struct name="TestPointer" doc="指针类型测试">
    <field name="self" type="TestPointer" useptr="false" doc=""/>
    <field name="stringValue" type="String" useptr="true" doc=""/>
    <field name="other" type="Custom" useptr="true" doc=""/>
    <field name="listI08" type="Vec-Int8" useptr="true" doc=""/>
    <field name="dictI08" type="Map-Int8-Int8" useptr="true" doc=""/>
    <field name="listNested" type="Vec-Vec-Vec-Vec-TestPointer" useptr="true" doc=""/>
    <field name="numberSingle" type="Float" useptr="true" doc=""/>
    <field name="enumValue" type="Gender" useptr="true" doc=""/>
  </struct>
  <struct name="ConfigRoot" alias="root" short="f" doc="">
    <field name="revision" type="String" value="1.0.0" doc=""/>
    <field name="list" type="TestList" doc=""/>
    <field name="dict" type="TestDict" doc=""/>
    <field name="nest" type="TestNest" doc=""/>
    <field name="info" type="Info" doc=""/>
    <field name="infox" type="InfoX" doc=""/>
  </struct>
  <struct name="Conflict" doc="">
    <field name="pi" type="Double" value="3.1415926" doc=""/>
  </struct>
  <struct name="InfoX" doc="Complex data structure">
    <field name="infos" type="Vec-Vec-Vec-Vec-Vec-Info" doc=""/>
    <field name="conflict_x" type="test.xyz::Conflict" doc="Two types with the same name."/>
    <field name="conflict_a" type="test.abc::Conflict" doc="Two types with the same name."/>
    <field name="mConflict" type="Map-test.abc::Conflict" doc=""/>
    <field name="info2d" type="Vec-Vec-Info" doc="2 dimension list"/>
    <field name="info3d" type="Vec-Vec-Vec-Info" doc="3 dimension list"/>
    <field name="info5d" type="Vec-Vec-Vec-Vec-Vec-Info" doc=""/>
    <field name="infovm" type="Vec-Map-Int16-Info" doc=""/>
    <field name="mvei" type="Map-Vec-Gender-Info" doc=""/>
    <field name="mive" type="Map-Info-Vec-Gender" doc=""/>
    <field name="mvive" type="Map-Vec-Info-Vec-Gender" doc=""/>
    <field name="vmvive" type="Vec-Map-Vec-Info-Vec-Gender" doc=""/>
  </struct>
</tns:package>

=== struqt/invar/res/example/rule/protoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:package name="test.protoc"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="invar.rule rule.xsd"
xmlns:tns="invar.rule">

  <struct name="Protoc2S" doc="客户端请求的公共数据" alias="protoc2S_">
    <field name="sessionId" type="String" doc="会话Id"/>
  </struct>

  <struct name="Protoc2C" doc="服务端响应的公共数据" alias="protoc2C_">
  </struct>
  
  <protoc name="TestProtoc" id="65535" doc="协议测试">
    <client>
      <field name="gender" type="Gender" doc="性别"/>
      <field name="message" type="String" doc="消息"/>
    </client>
    <server>
      <field name="info" type="Info" doc="数据"/>
    </server>
  </protoc>

</tns:package>
