=== struqt/invar/invar-core/src/main/resources/invar-snippet-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://invar.struqt.com/snippet/1.0"
        targetNamespace="http://invar.struqt.com/snippet/1.0">

	<xs:element name="root" type="tns:root">
		<xs:annotation>
			<xs:documentation>...</xs:documentation>
			<xs:appinfo>...</xs:appinfo>
		</xs:annotation>
	</xs:element>

	<xs:complexType name="root">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="redefine" type="tns:redefine" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="template" type="tns:template" minOccurs="0"
				maxOccurs="unbounded"/>
			<xs:element name="export" type="tns:export" minOccurs="0"
				maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="language" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="redefine">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element minOccurs="0" maxOccurs="unbounded" name="int8" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="int16" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="int32" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="int64" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="uint8" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="uint16" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="uint32" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="uint64" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="float" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="double" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="string" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="bool" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="vec" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="map" type="tns:redefine.item"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="dialect" type="tns:redefine.item"/>
		</xs:sequence>
		<xs:attribute name="genericOverride" type="xs:boolean" default="false" use="optional"/>
	</xs:complexType>
	<xs:complexType name="redefine.item">
		<xs:attribute name="pack" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="initValue" type="xs:string" use="optional"/>
		<xs:attribute name="generic" type="xs:string" use="optional"/>
		<xs:attribute name="include" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="export">
		<xs:attribute name="resPath" type="xs:string" use="required"/>
		<xs:attribute name="destDir" type="xs:string" use="required"/>
		<xs:attribute name="destName" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="template">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="key" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</schema>

=== struqt/invar/invar-core/src/main/resources/snippet/php/snippet.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root
  language="php"
  xmlns:tns="http://invar.struqt.com/snippet/1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://invar.struqt.com/snippet/1.0 http://struqt.com/xsd/invar-snippet-1.0.xsd">

  <!-- & &amp; < &lt; > &gt; " &quot; ' &apos; -->
  <export resPath="php/invar.codec.php" destDir="" destName="invar/invar.codec.php"/>

  <!-- Redefine 14 Invar buildin types to adapt PHP language -->
  <redefine>
    <int8 pack="php" type="int08" initValue="-1"/>
    <int16 pack="php" type="int16" initValue="-1"/>
    <int32 pack="php" type="int32" initValue="-1"/>
    <int64 pack="php" type="int64" initValue="-1"/>
    <uint8 pack="php" type="uint08" initValue="0"/>
    <uint16 pack="php" type="uint16" initValue="0"/>
    <uint32 pack="php" type="uint32" initValue="0"/>
    <uint64 pack="php" type="uint32" initValue="0"/>
    <float pack="php" type="float32" initValue="0.0"/>
    <double pack="php" type="float64" initValue="0.00"/>
    <string pack="php" type="string" initValue=""/>
    <bool pack="php" type="boolean" initValue="FALSE"/>
    <vec pack="php" type="list" generic="&lt;?&gt;" initValue=""/>
    <map pack="php" type="dict" generic="&lt;?,?&gt;" initValue=""/>
    <dialect pack="invar" type="BinaryWriter" include="invar/invar.codec.php"/>
    <dialect pack="invar" type="BinaryReader" include="invar/invar.codec.php"/>
  </redefine>
  <template key="trace.all.types">     <![CDATA[false]]></template>
  <template key="include.self">        <![CDATA[false]]></template>
  <template key="pack.name.nested">    <![CDATA[false]]></template>
  <template key="file.name.lowercase"> <![CDATA[false]]></template>
  <template key="capitalize.pack.head"><![CDATA[false]]></template>
  <template key="method.indent.num">   <![CDATA[1]]></template>
  <template key="one.pack.one.file">   <![CDATA[false]]></template>
  <template key="code.dir.flatten">    <![CDATA[false]]></template>
  <template key="code.dir.prefix">     <![CDATA[]]></template>
  <template key="pack.head.prefix">    <![CDATA[ true ]]></template>
  <template key="refer.spec">    <![CDATA[&]]></template>
  <template key="refer.invoke">  <![CDATA[.]]></template>
  <template key="refer.copy">    <![CDATA[(#name) = (#arg);]]></template>
  <template key="refer.const">   <![CDATA[const]]></template>
  <template key="pointer.spec">  <![CDATA[ ]]></template>
  <template key="pointer.invoke"><![CDATA[->]]></template>
  <template key="pointer.null">  <![CDATA[NULL]]></template>
  <template key="pointer.copy">  <![CDATA[(#name) = (#arg);]]></template>
  <template key="byte.yes">      <![CDATA[0x01]]></template>
  <template key="byte.non">      <![CDATA[0x00]]></template>

  <template key="init.any">    <![CDATA[ (#deft)     ]]></template>
  <template key="init.string"> <![CDATA[ '(#deft)'   ]]></template>
  <template key="init.struct"> <![CDATA[ new (#type) ]]></template>
  <template key="init.enum">   <![CDATA[ (#type)::(#name) ]]></template>
  <template key="init.vec">    <![CDATA[ array() ]]></template>
  <template key="init.map">    <![CDATA[ array() ]]></template>

  <template key="import"><![CDATA[ use \(#body);(#brk) ]]></template>
  <template key="import.body"><![CDATA[ (#pack)(#name) ]]></template>
  <template key="import.split"><![CDATA[ \ ]]></template>
  <template key="import.exclude.conflict"><![CDATA[true]]></template>
  <template key="import.exclude.same.pack"><![CDATA[true]]></template>
  <template key="import.exclude.packs"><![CDATA[php]]></template>
  <template key="doc">     <![CDATA[ /** (#doc) */    ]]></template>
  <template key="doc.line"><![CDATA[ (#space)// (#doc) ]]></template>
  <template key="struct.field.prefix"><![CDATA[ this-> ]]></template>
  <template key="struct.const.name.crc"><![CDATA[ self::CRC32 ]]></template>

  <template key="file"><![CDATA[
    <?php
	  /*===----------------------------*  PHP 5  *-------------------------------===//
    //
    //             THIS FILE IS GENERATED BY INVAR. DO NOT EDIT !!!
    //
    //===----------------------------------------------------------------------===*/
    (#blank)
    (#pack) ]]></template>
  <template key="file.include">      <![CDATA[ require_once dirname(__FILE__) . (#name);(#brk) ]]></template>
  <template key="file.include.wrap"> <![CDATA[ '/(#nameupper)(#value)' ]]></template>
  <template key="file.include.split"><![CDATA[ / ]]></template>
  <template key="file.pack.split">   <![CDATA[ \ ]]></template>
  <template key="file.pack"><![CDATA[
	namespace (#name);
    (#blank)
    (#includes)
    (#body) ]]></template>
  <template key="file.body"><![CDATA[
    (#import)
    (#enums)(#structs) ]]></template>

  <template key="enum.field"><![CDATA[
    (#tab)const (#name) = (#value);(#doc)
  ]]></template>
  <template key="enum"><![CDATA[
    abstract class (#name)
    {
    (#body)}
  ]]></template>
  <template key="struct"><![CDATA[
    [#addImport(struct; imports; invar::BinaryReader)]
    [#addImport(struct; imports; invar::BinaryWriter)]
    (#concat)
    (#blank)
    final class (#name)
    {
    (#tab)const CRC32 = 0x[#codeCRC32(struct)];
    (#blank)
    (#tab)static public function &CreateFromBytes (& $str)
    (#tab){
    (#tab)(#tab)$o = new (#name);
    (#tab)(#tab)$o->read(new BinaryReader($str));
    (#tab)(#tab)return $o;
    (#tab)}
    (#blank)
    [#codeFields (struct; fields)]
    [#codeNested (ctor.;  useFullName; struct; fields; imports)](#brk)
    [#codeNested (copy.;  useFullName; struct; fields; imports)](#brk)
    [#codeNested (read.;  useFullName; struct; fields; imports)](#brk)
    [#codeNested (write.; useFullName; struct; fields; imports)](#brk)
    [#codeGetters(struct; fields)]
    [#codeSetters(struct; fields)]
    [#codeNested (tostr.; useFullName; struct; fields; imports)](#brk)
    [#codeNested (tojson.; useFullName; struct; fields; imports)](#brk)
    [#codeNested (toxml.; useFullName; struct; fields; imports)](#brk)
    }
	]]></template>
  <template key="struct.meta"><![CDATA[ (#name) (#type) ]]></template>
  <template key="struct.field"><![CDATA[
    (#tab)private \$[#clampLen(lenFieldNameR; 24; (#namer) )] ;
    (#concat)/* [#codeMetaData(fields; (#index))]
    (#concat)[#codeLineDoc(fields; (#index))] */
  ]]></template>
  <template key="struct.setter"><![CDATA[
    (#blank)
    (#tab)[#codeDoc(fields; (#index))]
    (#tab)public function set[#upperHeadChar( (#namer) )](\$value) { \$(#name) = \$value; return \$this; }
  ]]></template>
  <template key="struct.getter"><![CDATA[
    (#blank)
    (#tab)[#codeDoc(fields; (#index))]
    (#tab)public function(#spec)get[#upperHeadChar( (#namer) )]() { return \$(#name); }
  ]]></template>

  <!-- Method Construct -->
  <template key="ctor.method"><![CDATA[
    (#tab)function __construct()
    (#tab){(#body)
    (#tab)}
    (#tab)/* End of constructor() */ ]]></template>
  <template key="ctor.any | ctor.vec | ctor.map"><![CDATA[
    \$[#clampLen(lenFieldName; 24; (#name))] = (#deft) ]]></template>
  <template key="ctor.ptr.any"><![CDATA[
    \$[#clampLen(lenFieldName; 24; (#name))] = (#null); ]]></template>
  <template key="ctor.ref.any"><![CDATA[ (#body); ]]></template>

  <!-- CopyFrom Method -->
  <template key="copy.method.arg"><![CDATA[ \$from ]]></template>
  <template key="copy.method"><![CDATA[ (#tab)public function &copy (& \$from)
    (#tab){
      (#tab)(#tab)if (\$this == \$from || \$from == (#null)) {
      (#tab)(#tab)(#tab)return this;
      (#tab)(#tab)}(#body)
      (#tab)(#tab)return \$this;
    (#tab)}
    (#tab)/* End of copy(...) */ ]]></template>
  <template key="copy.any"><![CDATA[ (#arg)->(#namer) ]]></template>
  <template key="copy.ref.any"><![CDATA[ \$(#name) = (#body); ]]></template>
  <template key="copy.ptr.any"><![CDATA[ \$(#name) = (#body);  ]]></template>
  <template key="copy.ptr.struct"><![CDATA[
    if ((#arg)->(#namer) != (#null)) {
    (#tab)\$(#name).copy((#body));
    } else {
    (#tab)\$(#name) = (#null);
    }
  ]]></template>
  <template key="copy.vec | copy.map"><![CDATA[ \$(#name) = array_merge((#arg)->(#namer)) ]]></template>
  <template key="copy.ref.vec | copy.ref.map"><![CDATA[
    if ((#arg)->(#namer) != (#null)) {
    (#tab)(#body);
    } else {
    (#tab)\$(#name) = array();
    } ]]></template>
  <template key="copy.ptr.vec | copy.ptr.map"><![CDATA[
    if ((#arg)->(#namer) != (#null)) {
    (#tab)\$(#name) = array();
    (#tab)(#body);
    } else {
    (#tab)\$(#name) = (#null);
    }
  ]]></template>

  <!-- Read bytes from a Stream -->
  <template key="read.method.arg"><![CDATA[ \$r ]]></template>
  <template key="read.method"><![CDATA[
    (#tab)public function &read (& \$r)
    (#tab){(#body)
    (#tab)(#tab)return \$this;
    (#tab)}
    (#tab)/* End of read(...) */
  ]]></template>
  <template key="read.int8">  <![CDATA[ (#arg)->readInt08()  ]]></template>
  <template key="read.int16"> <![CDATA[ (#arg)->readInt16()  ]]></template>
  <template key="read.int32"> <![CDATA[ (#arg)->readInt32()  ]]></template>
  <template key="read.int64"> <![CDATA[ (#arg)->readInt64()  ]]></template>
  <template key="read.uint8"> <![CDATA[ (#arg)->readUInt08() ]]></template>
  <template key="read.uint16"><![CDATA[ (#arg)->readUInt16() ]]></template>
  <template key="read.uint32"><![CDATA[ (#arg)->readUInt32() ]]></template>
  <template key="read.uint64"><![CDATA[ (#arg)->readUInt64() ]]></template>
  <template key="read.float"> <![CDATA[ (#arg)->readFloat32()]]></template>
  <template key="read.double"><![CDATA[ (#arg)->readFloat64()]]></template>
  <template key="read.string"><![CDATA[ (#arg)->readUTF()    ]]></template>
  <template key="read.bool">  <![CDATA[ (#arg)->readBoolean()]]></template>
  <template key="read.enum">  <![CDATA[ (#arg)->readInt32()  ]]></template>
  <template key="read.struct"><![CDATA[ \$(#name)->read((#arg)) ]]></template>
  <template key="read.nest.n|read.nest.k|read.nest.v"><![CDATA[ \$(#name) = (#body); ]]></template>
